#ifndef MOTOR_H

#define MOTOR_H

#define MOTOR_CONTROL_GPIO (11ULL)
#define MOTOR_CONTROL_GPIO_MASK (1ULL << MOTOR_CONTROL_GPIO)

#define BUTTON_GPIO (4ULL)
#define BUTTON_GPIO_MASK (1ULL << BUTTON_GPIO)

#define BUTTON_DEBOUNCE_TIME_MS 30

#endif
