#ifndef PHOTORESISTOR_H
#define PHOTORESISTOR_H

#define PHOTORESISTOR_ADC_UNIT ADC_UNIT_1
#define PHOTORESISTOR_ADC_CHANNEL ADC_CHANNEL_0
#define PHOTORESISTOR_ADC_ATTEN ADC_ATTEN_DB_12
#define PHOTORESISTOR_ADC_BITWIDTH ADC_BITWIDTH_DEFAULT
#define PHOTORESISTOR_SAMPLING_AMOUNT 8

#define ADC_VREF 3300
#define PHOTORESISTOR_FIXED_RESISTANCE_OHMS 10000

#define PHOTORESISTOR_SLEEP_TIME_MS 1000 * 60 * 5  // 5 minutes

void vPhotoresistorCreateTask();

#endif
